--[[
****************************************************************************************

esES.lua

esES localization strings for Chuck Norris Facts

File date: @file-date-iso@ 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: @project-version@

Currently maintained by:
http://www.wowace.com/projects/cnf/localization/translators/

Please update http://www.wowace.com/projects/cnf/localization/esES/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.

****************************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Chuck Norris Facts", "esES", false)

if not L then return end

--@localization(locale="esES", format="lua_additive_table", handle-unlocalized="ignore", escape-non-ascii=false, same-key-is-true=true)@
